### ISSUE TITLE
Update fresh bitcoin, remove one hop

### ISSUE THREAD

**Issue by MaxHillebrand** [zkSNACKs/WasabiStats#15]
https://github.com/nopara73/Dumplings/pull/13 removes the one hop remixes from the fresh bitcoin count.

This should be updated, an additional one hop volume chart could be added.

**Comment by molnard** [comment]
What's up with this @Szpoti ?

**Comment by Szpoti** [comment]
https://github.com/molnard/Dumplings/pull/16 was merged, fresh bitcoins was updated to one-hop, so this can be closed.
