### ISSUE TITLE
add min coinjoin input amount

### ISSUE THREAD

**Issue by MarnixCroes** [zkSNACKs/WasabiStats#20]
as the min input amount is now dependent on the mining fee market.
not just 5k sats.

good to know for users, not just an interesting statistic

**Comment by MarnixCroes** [comment]
brought it up before, maybe it was forgotten

**Comment by CAnorbo** [comment]
Done
![Screenshot 2024-01-11 at 09 06 57](https://github.com/zkSNACKs/WasabiStats/assets/56954907/97264fa5-e824-4a6e-98f9-a68b6586af85)

**Comment by Kruwed** [comment]
The min input amount displayed is not adjusting to the fee rate of the coinjoin, it shows 5000 even when rounds are paying over 100 sat/vbyte.

**Comment by CAnorbo** [comment]
I used: 
https://wasabiwallet.io/swagger/index.html

/WabiSabi/status

"allowedInputAmounts": {
  "min": {
    "satoshi": 0
  }
},

Should I use something else?

**Comment by molnard** [comment]
This minimum is only calculated in the client, so it is not visible on the API. 

https://github.com/molnard/WalletWasabi/blob/master/WalletWasabi/WabiSabi/Client/CoinJoinClient.cs#L161
