### ISSUE TITLE
Add Unspent Capacity

### ISSUE THREAD

**Issue by MaxHillebrand** [zkSNACKs/WasabiStats#4]
The value of coinjoin outputs that are still unspent.

**Comment by CAnorbo** [comment]
No function on Dumplings for this yet.

**Comment by MaxHillebrand** [comment]
There is, you might need to update your dumplings repo
https://github.com/nopara73/Dumplings/commit/7bb72f37a4aae3b92ef0c7bdd9aa160ab2843aac

**Comment by CAnorbo** [comment]
True!

CalculateUnspentCapacity(RPCClient rpc)

**Comment by molnard** [comment]
If you need this progress through the RR board.

**Comment by molnard** [comment]
Done?

**Comment by CAnorbo** [comment]
> Done?

Not yet.

**Comment by Szpoti** [comment]
A timer has been set to save and upload UnspentCapacity daily. They are accessable on Miranda.

**Comment by MaxHillebrand** [comment]
@CAnorbo please add the UI

**Comment by CAnorbo** [comment]
> @CAnorbo please add the UI

No data yet, in the database so we have to wait until tomorrow.

**Comment by molnard** [comment]
What's up with this? Done?

**Comment by Szpoti** [comment]
Yes on my part.

**Comment by CAnorbo** [comment]
Done.
